// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/36       [336420]
Creator        : leure
Date           : Wed Aug 16 19:20:52 2017
Host           : Linux lcgapp-slc6-x86-64-23.cern.ch 2.6.32-573.18.1.el6.x86_64 #1 SMP Wed Feb 10 14:02:50 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/bsTMVACDozen/myTMVA
Training events: 34803
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Btrk1Pt                       Btrk1Pt                       Btrk1Pt                       Btrk1Pt                                                         'F'    [0.500000238419,17.2004528046]
Btrk2Pt                       Btrk2Pt                       Btrk2Pt                       Btrk2Pt                                                         'F'    [0.500023543835,18.0035972595]
Bchi2cl                       Bchi2cl                       Bchi2cl                       Bchi2cl                                                         'F'    [0.0100008454174,0.999997913837]
BsvpvDistance/BsvpvDisErr     BsvpvDistance_D_BsvpvDisErr   BsvpvDistance/BsvpvDisErr     BsvpvDistance/BsvpvDisErr                                       'F'    [0.010027596727,5245.63525391]
Bd0/Bd0Err                    Bd0_D_Bd0Err                  Bd0/Bd0Err                    Bd0/Bd0Err                                                      'F'    [0.715755939484,58774.5976562]
cos(Bdtheta)                  cos_Bdtheta_                  cos(Bdtheta)                  cos(Bdtheta)                                                    'F'    [-1,1]
Bmu1pt                        Bmu1pt                        Bmu1pt                        Bmu1pt                                                          'F'    [0.717000067234,56.3763084412]
Bmu2pt                        Bmu2pt                        Bmu2pt                        Bmu2pt                                                          'F'    [0.711423754692,50.3804473877]
Bpt                           Bpt                           Bpt                           Bpt                                                             'F'    [0.0281025394797,117.906814575]
abs(Btktkmass-1.019455)       abs_Btktkmass_M_1.019455_     abs(Btktkmass-1.019455)       abs(Btktkmass-1.019455)                                         'F'    [4.01573174713e-07,0.0999938994646]
Blxy                          Blxy                          Blxy                          Blxy                                                            'F'    [-0.1291308254,2.32892298698]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Btrk1Pt", "Btrk2Pt", "Bchi2cl", "BsvpvDistance/BsvpvDisErr", "Bd0/Bd0Err", "cos(Bdtheta)", "Bmu1pt", "Bmu2pt", "Bpt", "abs(Btktkmass-1.019455)", "Blxy" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 3.06555666192486;
   fWeightMatrix0to1[1][0] = 2.10886349034988;
   fWeightMatrix0to1[2][0] = 0.935958638523386;
   fWeightMatrix0to1[3][0] = 1.76374943234681;
   fWeightMatrix0to1[4][0] = -2.14849061948513;
   fWeightMatrix0to1[5][0] = -1.38942711614502;
   fWeightMatrix0to1[6][0] = -0.830310471948367;
   fWeightMatrix0to1[7][0] = 1.61206004272682;
   fWeightMatrix0to1[8][0] = -1.6991830030576;
   fWeightMatrix0to1[9][0] = -1.10216379502911;
   fWeightMatrix0to1[10][0] = -1.81339654464284;
   fWeightMatrix0to1[11][0] = -0.937343080381388;
   fWeightMatrix0to1[12][0] = -1.4838817364704;
   fWeightMatrix0to1[13][0] = -1.03060092821924;
   fWeightMatrix0to1[14][0] = -0.944228188580615;
   fWeightMatrix0to1[15][0] = 1.88699865713841;
   fWeightMatrix0to1[0][1] = 3.27410436228834;
   fWeightMatrix0to1[1][1] = 1.80861926796235;
   fWeightMatrix0to1[2][1] = 0.233909485746222;
   fWeightMatrix0to1[3][1] = 1.42658338897892;
   fWeightMatrix0to1[4][1] = -0.189381486852228;
   fWeightMatrix0to1[5][1] = -0.785898036153235;
   fWeightMatrix0to1[6][1] = 0.700602746960323;
   fWeightMatrix0to1[7][1] = 0.0389443674345056;
   fWeightMatrix0to1[8][1] = -1.37581808254619;
   fWeightMatrix0to1[9][1] = -0.249619734582855;
   fWeightMatrix0to1[10][1] = 1.32937748178537;
   fWeightMatrix0to1[11][1] = -1.3166159653307;
   fWeightMatrix0to1[12][1] = -2.06604693804714;
   fWeightMatrix0to1[13][1] = -0.432611077133152;
   fWeightMatrix0to1[14][1] = 0.217911071826747;
   fWeightMatrix0to1[15][1] = 2.43461077577484;
   fWeightMatrix0to1[0][2] = 0.183512209059511;
   fWeightMatrix0to1[1][2] = -0.200696006383383;
   fWeightMatrix0to1[2][2] = 0.167966116662029;
   fWeightMatrix0to1[3][2] = -0.299746403714339;
   fWeightMatrix0to1[4][2] = -1.07697695746024;
   fWeightMatrix0to1[5][2] = 1.84661608861909;
   fWeightMatrix0to1[6][2] = -1.16570861008665;
   fWeightMatrix0to1[7][2] = 0.740227314979993;
   fWeightMatrix0to1[8][2] = 0.840826233805846;
   fWeightMatrix0to1[9][2] = 0.697387245135011;
   fWeightMatrix0to1[10][2] = 1.82526031067395;
   fWeightMatrix0to1[11][2] = 0.447179142408997;
   fWeightMatrix0to1[12][2] = -0.529591518436327;
   fWeightMatrix0to1[13][2] = -1.05599787264987;
   fWeightMatrix0to1[14][2] = -0.00588839223174126;
   fWeightMatrix0to1[15][2] = 0.112955789072036;
   fWeightMatrix0to1[0][3] = 1.16592168277761;
   fWeightMatrix0to1[1][3] = 1.66771035879685;
   fWeightMatrix0to1[2][3] = 1.67543425192785;
   fWeightMatrix0to1[3][3] = 1.29293927244647;
   fWeightMatrix0to1[4][3] = -1.87370531894752;
   fWeightMatrix0to1[5][3] = 1.20387198849948;
   fWeightMatrix0to1[6][3] = -1.86971991672382;
   fWeightMatrix0to1[7][3] = -1.2525720062266;
   fWeightMatrix0to1[8][3] = -0.796219007058326;
   fWeightMatrix0to1[9][3] = -1.82594587552391;
   fWeightMatrix0to1[10][3] = 1.31296204229626;
   fWeightMatrix0to1[11][3] = 0.0403811253009597;
   fWeightMatrix0to1[12][3] = -1.67399806695735;
   fWeightMatrix0to1[13][3] = 0.11423528992933;
   fWeightMatrix0to1[14][3] = -1.18212331074937;
   fWeightMatrix0to1[15][3] = 0.527358721076518;
   fWeightMatrix0to1[0][4] = 5.78746182044775;
   fWeightMatrix0to1[1][4] = -0.0892936314697387;
   fWeightMatrix0to1[2][4] = 0.189622092859351;
   fWeightMatrix0to1[3][4] = -1.18989539764438;
   fWeightMatrix0to1[4][4] = 0.21169188042699;
   fWeightMatrix0to1[5][4] = -0.746684141531542;
   fWeightMatrix0to1[6][4] = -0.779337894136227;
   fWeightMatrix0to1[7][4] = -1.46907841328216;
   fWeightMatrix0to1[8][4] = 0.862990649024765;
   fWeightMatrix0to1[9][4] = 1.01620249479434;
   fWeightMatrix0to1[10][4] = 1.1157100722564;
   fWeightMatrix0to1[11][4] = -1.31199735911444;
   fWeightMatrix0to1[12][4] = -2.12538304261365;
   fWeightMatrix0to1[13][4] = -2.52216616733797;
   fWeightMatrix0to1[14][4] = 0.194629181238073;
   fWeightMatrix0to1[15][4] = 1.49128636407491;
   fWeightMatrix0to1[0][5] = 7.9132207806616;
   fWeightMatrix0to1[1][5] = 0.44211997128684;
   fWeightMatrix0to1[2][5] = 0.946563029927864;
   fWeightMatrix0to1[3][5] = -0.786199897677248;
   fWeightMatrix0to1[4][5] = -0.0842647904537358;
   fWeightMatrix0to1[5][5] = -0.0811521944364196;
   fWeightMatrix0to1[6][5] = 1.10953136652743;
   fWeightMatrix0to1[7][5] = 0.277084233548581;
   fWeightMatrix0to1[8][5] = -2.02144235758318;
   fWeightMatrix0to1[9][5] = -1.48771955766653;
   fWeightMatrix0to1[10][5] = -0.255944685828659;
   fWeightMatrix0to1[11][5] = 0.0789195035730061;
   fWeightMatrix0to1[12][5] = 1.48604158615201;
   fWeightMatrix0to1[13][5] = -1.73558589123993;
   fWeightMatrix0to1[14][5] = -1.05819303524627;
   fWeightMatrix0to1[15][5] = 4.67891987113978;
   fWeightMatrix0to1[0][6] = -0.962325086945076;
   fWeightMatrix0to1[1][6] = -1.41788386944108;
   fWeightMatrix0to1[2][6] = -1.44986048903905;
   fWeightMatrix0to1[3][6] = 0.113331962382435;
   fWeightMatrix0to1[4][6] = -2.79284974738922;
   fWeightMatrix0to1[5][6] = -1.64005843782543;
   fWeightMatrix0to1[6][6] = 0.676509335520554;
   fWeightMatrix0to1[7][6] = 1.54956331650837;
   fWeightMatrix0to1[8][6] = -1.39127796408849;
   fWeightMatrix0to1[9][6] = 1.50161061749515;
   fWeightMatrix0to1[10][6] = -1.12323746687864;
   fWeightMatrix0to1[11][6] = -1.32943857807421;
   fWeightMatrix0to1[12][6] = -0.316078173016735;
   fWeightMatrix0to1[13][6] = -0.161315597168144;
   fWeightMatrix0to1[14][6] = -1.33737538039915;
   fWeightMatrix0to1[15][6] = 0.919031041321524;
   fWeightMatrix0to1[0][7] = -1.16774822290362;
   fWeightMatrix0to1[1][7] = 0.685383558943601;
   fWeightMatrix0to1[2][7] = -1.30726869161939;
   fWeightMatrix0to1[3][7] = 1.83478763955728;
   fWeightMatrix0to1[4][7] = -0.0896753122745534;
   fWeightMatrix0to1[5][7] = -0.909579900841282;
   fWeightMatrix0to1[6][7] = 0.763341906682565;
   fWeightMatrix0to1[7][7] = -0.770179954367462;
   fWeightMatrix0to1[8][7] = -1.51723791926693;
   fWeightMatrix0to1[9][7] = 0.111211377450092;
   fWeightMatrix0to1[10][7] = -0.524876555362336;
   fWeightMatrix0to1[11][7] = 1.29201766758839;
   fWeightMatrix0to1[12][7] = 0.567809056276746;
   fWeightMatrix0to1[13][7] = -0.459189875992365;
   fWeightMatrix0to1[14][7] = -0.387354245808965;
   fWeightMatrix0to1[15][7] = 0.210269229378774;
   fWeightMatrix0to1[0][8] = 1.31684260904241;
   fWeightMatrix0to1[1][8] = 1.1889322305834;
   fWeightMatrix0to1[2][8] = 0.237929496329897;
   fWeightMatrix0to1[3][8] = -1.80103852043436;
   fWeightMatrix0to1[4][8] = 0.202733287770906;
   fWeightMatrix0to1[5][8] = -1.37036282520354;
   fWeightMatrix0to1[6][8] = 0.0231143863165845;
   fWeightMatrix0to1[7][8] = 1.259534918333;
   fWeightMatrix0to1[8][8] = 1.59249654944405;
   fWeightMatrix0to1[9][8] = -1.93960101456487;
   fWeightMatrix0to1[10][8] = 0.175097021826266;
   fWeightMatrix0to1[11][8] = 1.08629355836932;
   fWeightMatrix0to1[12][8] = 1.39735616136251;
   fWeightMatrix0to1[13][8] = -0.332255450586804;
   fWeightMatrix0to1[14][8] = -1.33989624382472;
   fWeightMatrix0to1[15][8] = -0.273879880525583;
   fWeightMatrix0to1[0][9] = -2.76426368585919;
   fWeightMatrix0to1[1][9] = 1.29552697277843;
   fWeightMatrix0to1[2][9] = 0.716434075430043;
   fWeightMatrix0to1[3][9] = -0.48097764104325;
   fWeightMatrix0to1[4][9] = -0.628200016052383;
   fWeightMatrix0to1[5][9] = -0.0836547631272709;
   fWeightMatrix0to1[6][9] = -1.31544681989383;
   fWeightMatrix0to1[7][9] = 0.788803059378692;
   fWeightMatrix0to1[8][9] = 1.30825789639986;
   fWeightMatrix0to1[9][9] = -0.669508294632941;
   fWeightMatrix0to1[10][9] = -0.648920440728743;
   fWeightMatrix0to1[11][9] = 0.34158906503117;
   fWeightMatrix0to1[12][9] = 0.863343387575664;
   fWeightMatrix0to1[13][9] = 0.428954236229538;
   fWeightMatrix0to1[14][9] = 1.4686555761632;
   fWeightMatrix0to1[15][9] = -2.54097755878648;
   fWeightMatrix0to1[0][10] = 5.12137361286594;
   fWeightMatrix0to1[1][10] = 0.946956315044909;
   fWeightMatrix0to1[2][10] = 0.531630947474417;
   fWeightMatrix0to1[3][10] = 0.605663423245281;
   fWeightMatrix0to1[4][10] = 0.722539327592374;
   fWeightMatrix0to1[5][10] = -0.541414968514967;
   fWeightMatrix0to1[6][10] = -0.642057429301603;
   fWeightMatrix0to1[7][10] = 2.03850723248721;
   fWeightMatrix0to1[8][10] = -1.06835535867369;
   fWeightMatrix0to1[9][10] = -0.705175339579762;
   fWeightMatrix0to1[10][10] = 1.36701353250213;
   fWeightMatrix0to1[11][10] = 0.316180647515159;
   fWeightMatrix0to1[12][10] = -0.397888236542207;
   fWeightMatrix0to1[13][10] = 0.825326568210877;
   fWeightMatrix0to1[14][10] = 1.39079116621005;
   fWeightMatrix0to1[15][10] = -0.55243697598534;
   fWeightMatrix0to1[0][11] = 6.05297023864733;
   fWeightMatrix0to1[1][11] = -0.214850647830138;
   fWeightMatrix0to1[2][11] = 0.446801774764492;
   fWeightMatrix0to1[3][11] = -1.72051862806567;
   fWeightMatrix0to1[4][11] = -0.8346771028719;
   fWeightMatrix0to1[5][11] = 1.27343335989091;
   fWeightMatrix0to1[6][11] = 1.84016061330746;
   fWeightMatrix0to1[7][11] = -1.35480520798303;
   fWeightMatrix0to1[8][11] = -0.415258129170675;
   fWeightMatrix0to1[9][11] = -0.5036580430861;
   fWeightMatrix0to1[10][11] = 0.507324810916966;
   fWeightMatrix0to1[11][11] = 2.38724003553154;
   fWeightMatrix0to1[12][11] = -0.0706843660421081;
   fWeightMatrix0to1[13][11] = -0.15336469324931;
   fWeightMatrix0to1[14][11] = -0.638887330460364;
   fWeightMatrix0to1[15][11] = -0.268961525343148;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.794427402024126;
   fWeightMatrix1to2[0][1] = 1.08598667229726;
   fWeightMatrix1to2[0][2] = 0.0131401809113631;
   fWeightMatrix1to2[0][3] = -0.666902729918667;
   fWeightMatrix1to2[0][4] = -1.80130734055421;
   fWeightMatrix1to2[0][5] = 0.890676777142491;
   fWeightMatrix1to2[0][6] = -0.0151652416259488;
   fWeightMatrix1to2[0][7] = -1.18890041209391;
   fWeightMatrix1to2[0][8] = 0.0569628427755244;
   fWeightMatrix1to2[0][9] = 0.0171972295110572;
   fWeightMatrix1to2[0][10] = 0.000230504857603406;
   fWeightMatrix1to2[0][11] = -1.80519093179257;
   fWeightMatrix1to2[0][12] = 0.883925128589306;
   fWeightMatrix1to2[0][13] = 0.0631385618407705;
   fWeightMatrix1to2[0][14] = -0.11758879270694;
   fWeightMatrix1to2[0][15] = -0.345731317827566;
   fWeightMatrix1to2[0][16] = 1.51581991774282;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.500091910362;
   fMax_1[0][0] = 17.2004528046;
   fMin_1[1][0] = 0.500000238419;
   fMax_1[1][0] = 9.61096382141;
   fMin_1[2][0] = 0.500000238419;
   fMax_1[2][0] = 17.2004528046;
   fMin_1[0][1] = 0.50191628933;
   fMax_1[0][1] = 18.0035972595;
   fMin_1[1][1] = 0.500023543835;
   fMax_1[1][1] = 14.7609272003;
   fMin_1[2][1] = 0.500023543835;
   fMax_1[2][1] = 18.0035972595;
   fMin_1[0][2] = 0.0101060122252;
   fMax_1[0][2] = 0.999833285809;
   fMin_1[1][2] = 0.0100008454174;
   fMax_1[1][2] = 0.999997913837;
   fMin_1[2][2] = 0.0100008454174;
   fMax_1[2][2] = 0.999997913837;
   fMin_1[0][3] = 3.53304409981;
   fMax_1[0][3] = 3943.46826172;
   fMin_1[1][3] = 0.010027596727;
   fMax_1[1][3] = 5245.63525391;
   fMin_1[2][3] = 0.010027596727;
   fMax_1[2][3] = 5245.63525391;
   fMin_1[0][4] = 26.3300800323;
   fMax_1[0][4] = 58774.5976562;
   fMin_1[1][4] = 0.715755939484;
   fMax_1[1][4] = 27708.6484375;
   fMin_1[2][4] = 0.715755939484;
   fMax_1[2][4] = 58774.5976562;
   fMin_1[0][5] = -0.989427983761;
   fMax_1[0][5] = 1;
   fMin_1[1][5] = -1;
   fMax_1[1][5] = 1;
   fMin_1[2][5] = -1;
   fMax_1[2][5] = 1;
   fMin_1[0][6] = 0.743135333061;
   fMax_1[0][6] = 49.3333969116;
   fMin_1[1][6] = 0.717000067234;
   fMax_1[1][6] = 56.3763084412;
   fMin_1[2][6] = 0.717000067234;
   fMax_1[2][6] = 56.3763084412;
   fMin_1[0][7] = 0.726923644543;
   fMax_1[0][7] = 31.9218502045;
   fMin_1[1][7] = 0.711423754692;
   fMax_1[1][7] = 50.3804473877;
   fMin_1[2][7] = 0.711423754692;
   fMax_1[2][7] = 50.3804473877;
   fMin_1[0][8] = 7.00321578979;
   fMax_1[0][8] = 104.806182861;
   fMin_1[1][8] = 0.0281025394797;
   fMax_1[1][8] = 117.906814575;
   fMin_1[2][8] = 0.0281025394797;
   fMax_1[2][8] = 117.906814575;
   fMin_1[0][9] = 1.62498474765e-06;
   fMax_1[0][9] = 0.0925285369158;
   fMin_1[1][9] = 4.01573174713e-07;
   fMax_1[1][9] = 0.0999938994646;
   fMin_1[2][9] = 4.01573174713e-07;
   fMax_1[2][9] = 0.0999938994646;
   fMin_1[0][10] = -0.0468452014029;
   fMax_1[0][10] = 1.41659402847;
   fMin_1[1][10] = -0.1291308254;
   fMax_1[1][10] = 2.32892298698;
   fMin_1[2][10] = -0.1291308254;
   fMax_1[2][10] = 2.32892298698;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
